export const LANGUAGE_CONSTANTS = {
  en: {
    gptSearchButton: "Search",
    gptSearchPlaceHolder: "What movies do you want to watch?",
    gptSearchNavButton: "GPT Search",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    emailPlaceHd: "Email Address",
    pwdPlaceHd: "Password",
    fullNamePlaceHd: "Full Name",
    signInPageTxt: "New to Netflix? Sign Up Now",
    signUpPageTxt: "Already Registered? Sign In Now",
    pwdCheck1: "Should have at least 8 characters",
    pwdCheck2: "Use at least one upper case",
    pwdCheck3: "Use at least one lower case",
    pwdCheck4: "Use one special character",
    pwdCheck5: "Use at least one number",
    emailErr: "Email ID not valid",
    pwdErr: "Password not valid",
    profileSlogan: "Who's Watching?",
    manageProfile: "Manage Profiles",
    doneProfile: "Done",
    addProfile: "Add Profile",
    searchError: "Something Went Wrong, Please Try Again.",
  },
  tamil: {
    gptSearchButton: "தேடு",
    gptSearchPlaceHolder:
      "நீங்கள் என்ன திரைப்படங்களைப் பார்க்க விரும்புகிறீர்கள்?",
    gptSearchNavButton: "GPT தேடு",
    signIn: "உள்நுழைக",
    signUp: "பதிவு செய்",
    signOut: "வெளியேறு",
    emailPlaceHd: "மின்னஞ்சல் முகவரி",
    pwdPlaceHd: "கடவுச்சொல்",
    fullNamePlaceHd: "முழு பெயர்",
    signInPageTxt: "Netflix க்கு புதியவரா? இப்பொது பதிவு செய்",
    signUpPageTxt: "ஏற்கனவே பதிவு செய்யப்பட்டது? இப்போது உள்நுழையவும்",
    pwdCheck1: "குறைந்தது 8 எழுத்துகள் இருக்க வேண்டும்",
    pwdCheck2: "குறைந்தபட்சம் ஒரு பெரிய வழக்கையாவது பயன்படுத்தவும்",
    pwdCheck3: "குறைந்தபட்சம் ஒரு சிறிய எழுத்தையாவது பயன்படுத்தவும்",
    pwdCheck4: "ஒரு சிறப்பு எழுத்தைப் பயன்படுத்தவும்",
    pwdCheck5: "குறைந்தது ஒரு எண்ணையாவது பயன்படுத்தவும்",
    emailErr: "மின்னஞ்சல் ஐடி செல்லாது",
    pwdErr: "கடவுச்சொல் செல்லாது",
    profileSlogan: "யார் பார்க்கிறார்கள்?",
    manageProfile: "சுயவிவரங்களை நிர்வகிக்கவும்",
    doneProfile: "முடிந்தது",
    addProfile: "சுயவிவரத்தை உருவாக்கவும்",
    searchError: "ஏதோ தவறாகிவிட்டது, மீண்டும் முயற்சிக்கவும்.",
  },
  hindi: {
    gptSearchButton: "खोज",
    gptSearchPlaceHolder: "आप कौन सी फिल्में देखना चाहते हैं?",
    gptSearchNavButton: "GPT खोज",
    signIn: "दाखिल करना",
    signUp: "साइन अप करें",
    signOut: "साइन आउट",
    emailPlaceHd: "मेल पता",
    pwdPlaceHd: "पासवर्ड",
    fullNamePlaceHd: "पूरा नाम",
    signInPageTxt: "नेटफ्लिक्स पर नए हैं? अभी साइनअप करें",
    signUpPageTxt: "पहले से ही पंजीकृत? अब साइन इन करो",
    pwdCheck1: "कम से कम 8 अक्षर होने चाहिए",
    pwdCheck2: "कम से कम एक अपरकेस का प्रयोग करें",
    pwdCheck3: "कम से कम एक लोअरकेस का प्रयोग करें",
    pwdCheck4: "एक विशेष वर्ण का प्रयोग करें",
    pwdCheck5: "कम से कम एक नंबर का प्रयोग करें",
    emailErr: "ईमेल आईडी मान्य नहीं है",
    pwdErr: "पासवर्ड मान्य नहीं है",
    profileSlogan: "कौन देख रहा है?",
    manageProfile: "प्रोफ़ाइल प्रबंधित करें",
    doneProfile: "हो गया",
    addProfile: "प्रोफ़ाइल जोड़ें",
    searchError: "कुछ गड़बड़ हुई है। कृपया दोबारा प्रयास करें।",
  },
};
